"""Initial revision

Revision ID: da30aeec3888
Revises: a262e195d2e1
Create Date: 2025-11-05 22:17:12.014679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da30aeec3888'
down_revision: Union[str, Sequence[str], None] = 'a262e195d2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraphs', sa.Column('title', sa.String(), nullable=False))
    op.add_column('paragraphs', sa.Column('content', sa.String(), nullable=False))
    op.drop_column('paragraphs', 'chapter_content')
    op.drop_column('paragraphs', 'chapter_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paragraphs', sa.Column('chapter_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('paragraphs', sa.Column('chapter_content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('paragraphs', 'content')
    op.drop_column('paragraphs', 'title')
    # ### end Alembic commands ###
